### ISSUE TITLE
Could I have nps?

### ISSUE THREAD

**Issue by kentcdodds** [tmpvar/npmsearch-cli#2]
Hi @tmpvar!
I have a module called [`p-s`](https://www.npmjs.com/package/p-s) (short for `package-scripts`) that I want to rename `nps` (short for `npm-package-scripts`) for various reasons. I noticed that you own this package name. Would you be willing to give me ownership of this module on npm?

I'd be happy to leave the existing stuff up there on the registry as `0.1.1` and I'd just publish my module as `1.0.0`. So if anyone's using the old module, they can continue to do so. I'll also add a note to my README indicating that you provided the name and directing people to where they can find and install your old module.

Thanks for your consideration!

**Comment by tmpvar** [comment]
done
